name: 'Add item (preview)'
description: 'Help us to improve the listing'
title: 'New item'
labels: ['needs investigate']
- type: textarea
  attributes:
    label: BoothのURL
    description: BoothのURLを記入してください。
    options:
    - label: "魚拓サイトのURLを記入します"
      required: true
- type: textarea
  attributes:
    label: 魚拓サイトのURL
    description: gyo.tc など、対象のページをキャプチャした魚拓サイトへのURLを記入してください。
    options:
    - label: "魚拓サイトのURLを記入します"
      required: true
