name: 'Add item (preview)'
description: 'Help us to improve the listing'
title: 'New item'
labels: ['needs investigate']
body:
- type: textarea
  attributes:
    label: BoothのURL
    description: BoothのURLを記入してください。
    options:
  validations:  
    required: true
- type: textarea
  attributes:
    label: 魚拓サイトのURL
    description: gyo.tc など、対象のページをキャプチャした魚拓サイトへのURLを記入してください。
  validations:
    required: true
